config/routes.rb
Image3::Application.routes.draw do
  resources :imageings

  resources :shops

  resources :items

  resources :attaches

  get 'images' => 'images#index'
  get 'images/:id/:style.:extension' => 'images#show'

  

end

app/models/attach.rb
class Attach < ActiveRecord::Base
  has_attached_file :photo, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png],
      :large2 => ["400x400>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    },
	#:path => ":rails_root/public/system/:id/:style.:extension",
	#:url  => "#{ActionController::Base.relative_url_root}/system/:id/:style.:extension"
	:path => "/Users/matsuhisa/Documents/work/ruby/temp_images/:id/:style.:extension",
	:url  => "/images/:id/:style.:extension"
  }

  has_many :imageings
end

app/controllers/attaches_controller.rb
class AttachesController < ApplicationController
  before_action :set_attach, only: [:show, :edit, :update, :destroy]

  # GET /attaches
  # GET /attaches.json
  def index
    @attaches = Attach.all
  end

  # GET /attaches/1
  # GET /attaches/1.json
  def show
  end

  # GET /attaches/new
  def new
    @attach = Attach.new
  end

  # GET /attaches/1/edit
  def edit
  end

  # POST /attaches
  # POST /attaches.json
  def create
    @attach = Attach.new(attach_params)

    respond_to do |format|
      if @attach.save
        format.html { redirect_to @attach, notice: 'Attach was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attach }
      else
        format.html { render action: 'new' }
        format.json { render json: @attach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attaches/1
  # PATCH/PUT /attaches/1.json
  def update
    respond_to do |format|
      if @attach.update(attach_params)
        format.html { redirect_to @attach, notice: 'Attach was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attaches/1
  # DELETE /attaches/1.json
  def destroy
    @attach.destroy
    respond_to do |format|
      format.html { redirect_to attaches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attach
      @attach = Attach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attach_params
      params.require(:attach).permit(:file, :title, :description, :photo)
    end
end

app/helpers/attaches_helper.rb
module AttachesHelper
end

app/views/attaches/_form.html.erb
<%= form_for @attach, :html => { :multipart => true } do |f| %>
  <% if @attach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attach.errors.count, "error") %> prohibited this attach from being saved:</h2>

      <ul>
      <% @attach.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attaches/edit.html.erb
<h1>Editing attach</h1>

<%= render 'form' %>

<%= link_to 'Show', @attach %> |
<%= link_to 'Back', attaches_path %>

app/views/attaches/index.html.erb
<h1>Listing attaches</h1>

<table>
  <thead>
    <tr>
      <th>File</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attaches.each do |attach| %>
      <tr>
        <td><%= attach.file %></td>
        <td><%= attach.title %></td>
        <td><%= attach.description %></td>
        <td><%= link_to 'Show', attach %></td>
        <td><%= link_to 'Edit', edit_attach_path(attach) %></td>
        <td><%= link_to 'Destroy', attach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attach', new_attach_path %>

app/views/attaches/new.html.erb
<h1>New attach</h1>

<%= render 'form' %>

<%= link_to 'Back', attaches_path %>

app/views/attaches/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @attach.photo(:large) %>
<%= image_tag @attach.photo(:thumb) %>


<p>
  <strong>File:</strong>
  <%= @attach.file %>
</p>

<p>
  <strong>Title:</strong>
  <%= @attach.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attach.description %>
</p>

<%= link_to 'Edit', edit_attach_path(@attach) %> |
<%= link_to 'Back', attaches_path %>