config/routes.rb
Image3::Application.routes.draw do
  resources :imageings

  resources :shops

  resources :items

  resources :attaches

  get 'images' => 'images#index'
  get 'images/:id/:style.:extension' => 'images#show'

  

end

app/models/imageing.rb
class Imageing < ActiveRecord::Base
end

app/controllers/imageings_controller.rb
class ImageingsController < ApplicationController
  before_action :set_imageing, only: [:show, :edit, :update, :destroy]

  # GET /imageings
  # GET /imageings.json
  def index
    @imageings = Imageing.all
  end

  # GET /imageings/1
  # GET /imageings/1.json
  def show
  end

  # GET /imageings/new
  def new
    @imageing = Imageing.new
  end

  # GET /imageings/1/edit
  def edit
  end

  # POST /imageings
  # POST /imageings.json
  def create
    @imageing = Imageing.new(imageing_params)

    respond_to do |format|
      if @imageing.save
        format.html { redirect_to @imageing, notice: 'Imageing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @imageing }
      else
        format.html { render action: 'new' }
        format.json { render json: @imageing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imageings/1
  # PATCH/PUT /imageings/1.json
  def update
    respond_to do |format|
      if @imageing.update(imageing_params)
        format.html { redirect_to @imageing, notice: 'Imageing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @imageing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imageings/1
  # DELETE /imageings/1.json
  def destroy
    @imageing.destroy
    respond_to do |format|
      format.html { redirect_to imageings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imageing
      @imageing = Imageing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imageing_params
      params.require(:imageing).permit(:parent_id, :parent, :status)
    end
end

app/helpers/imageings_helper.rb
module ImageingsHelper
end

app/views/imageings/_form.html.erb
<%= form_for(@imageing) do |f| %>
  <% if @imageing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imageing.errors.count, "error") %> prohibited this imageing from being saved:</h2>

      <ul>
      <% @imageing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.text_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :parent_type %><br>
    <%= f.text_field :parent_type %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imageings/edit.html.erb
<h1>Editing imageing</h1>

<%= render 'form' %>

<%= link_to 'Show', @imageing %> |
<%= link_to 'Back', imageings_path %>

app/views/imageings/index.html.erb
<h1>Listing imageings</h1>

<table>
  <thead>
    <tr>
      <th>Parent</th>
      <th>Parent</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @imageings.each do |imageing| %>
      <tr>
        <td><%= imageing.parent_id %></td>
        <td><%= imageing.parent %></td>
        <td><%= imageing.status %></td>
        <td><%= link_to 'Show', imageing %></td>
        <td><%= link_to 'Edit', edit_imageing_path(imageing) %></td>
        <td><%= link_to 'Destroy', imageing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imageing', new_imageing_path %>

app/views/imageings/new.html.erb
<h1>New imageing</h1>

<%= render 'form' %>

<%= link_to 'Back', imageings_path %>

app/views/imageings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent:</strong>
  <%= @imageing.parent_id %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @imageing.parent %>
</p>

<p>
  <strong>Status:</strong>
  <%= @imageing.status %>
</p>

<%= link_to 'Edit', edit_imageing_path(@imageing) %> |
<%= link_to 'Back', imageings_path %>